### ISSUE TITLE
Invalid zip

### ISSUE THREAD

**Issue by Uppermill** [MERG-DEV/CANPiWi#2]
I've tried to download the zip file. The final size is 39KB and my windows 10 PC cannot open it as it is invalid. Can you help>

**Comment by spikyian** [comment]
Sorry I don't know anything about the CANPiWi

Ian

**Comment by pnbgit** [comment]
There is an image file for the CANPiWi on the MERG dropbox which is referenced from the CANPiWi wiki page. However, it is not the latest version.  Amauri has promised to update it.  I have a more recent version which Amauri sent me, but I don't have direct write access to the MERG dropbox account so I can't upload it their myself. It is too big to upload to Gibhub, AFAIK.

**Comment by amaurial** [comment]
Is this still an issue?

Amauri

**Comment by Uppermill** [comment]
Please close the issue.

Regards

Allan
